### ISSUE TITLE
Did you tried this?!

### ISSUE THREAD

**Issue by moritzmoritz98** [philippnormann1337/whats-their-favorite-lang#1]
```python
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

x = Image.open('./bild.png')

h = plt.hist(np.reshape(np.array(x),-1), bins=255)[0]

comic = np.sum(np.abs(h / np.sum(h) - 1/255))
print(comic)
```

**Comment by moritzmoritz98** [comment]
COULD YOU HAVE A LOOK ON THAT YET? :pray:

**Comment by philippnormann1337** [comment]
No, to be honest I don't fully understand the issue 😅
Do you mind explaining what kind of change you are suggesting and what issue the suggested code is trying to solve? 🤔
P.S.: If you have specific code suggestions, I would much rather prefer a pull request 🤗

**Comment by moritzmoritz98** [comment]
Glad to hear your welcome of my contribution! I'm honored to participate in such a hilarious project.

However and after further investigations, I have to admit that your project still faces some major issues when it comes to the quality of the crawled GitHub profile images.
 
In your best interest, I recommend you to conduct a second and deeper look on as much as those 7 lines of code in case enhancing your project is a considerable option.
I'll have faith in you figuring out what appropriate next steps might be and leave with best wishes,
Your Mo

**Comment by splieth** [comment]
Besides that this issue seems stale, it appears kind of useless - can’t we close it?

**Comment by philippnormann1337** [comment]
@splieth Yes, we can!

**Comment by moritzmoritz98** [comment]
I'm not quite sure about that being a suitable reaction to concerned collaborators.
